apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pythontest 
  janus-idp.io/tekton: pythontest
  backstage.io/kubernetes-id: pythontest
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pythontest
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  