apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pythontest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pythontest 
  name: pythontest
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pythontest 
